name: Web application build

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: Setup dotnet
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: '8.0.x'
     - name: Install dependencies
       run: dotnet restore
     - name: Build
       run: dotnet build --no-restore
     - name: Test with the dotnet CLI
       run: dotnet test --no-build
