name: Run Azure CLI Login with OpenID Connect
on: [push]
     
jobs: 
  test:
    permissions:
      id-token: write # Require write permission to Fetch an OIDC token.

    runs-on: ubuntu-latest
    steps:
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-secret: ${{ secrets.CLIENTSECRET }}
        
        client-id: ${{ vars.CLIENTID }}
        tenant-id: ${{ vars.TENANTID }}
        subscription-id: ${{ vars.SUBSCRIPTIONID }}
  
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
